### ISSUE TITLE
add eslint rule to forbid  `const foo = () =>` in favor of `function foo() `

### ISSUE THREAD

**Issue by bard** [gitcoinco/allo-indexer#147]
Mostly to guard against @bard's muscle memory.

**Comment by Franqsanz** [comment]
Hi, I would think that with this standard should work:  `"func-style": ["error", "declaration", { "allowArrowFunctions": false }],`

**Comment by bard** [comment]
If I read docs correctly, that would still allow code like this to be written, being an expression and not a declaration:

```ts
[1,2,3].forEach((i) => { console.log(i); }
```

Correct?

If you fancy opening a PR, that's most welcome, but even if not, thanks a lot for the pointer @Franqsanz!
