### ISSUE TITLE
Indexer: cap GitcoinVote tokens at 10 votes per project per wallet

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/allo-indexer#260]
**User Story:**
As a Program Manager for the Fantom round 
I want to be able to cap the amount of votes counted per wallet with a verified Passport score 
so that I can prevent against users who might farm the valueless token in order to support their favorite projects 

**Acceptance Criteria**
GIVEN that I am donating in Fantom's QF round
WHEN I donate 
THEN I see I can only donate up to 10 GcV tokens to 1 project per wallet

**Product & Design Links:**

**Tech Details:**
1 - if someone votes directly to the contract with 20 tokens, we will show 20 tokens in the UI
2 - but during the QF calculation we will use it as a 10 token vote

* Fantom's valueless token - GitcoinVote (GcV) contract address: 0x83791638da5EB2fAa432aff1c65fbA47c5D29510 

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by michellema1208** [comment]
Update from 8/25: Spun up a test round and donated to two projects following the below parameters: 

Round: https://manager.gitcoin.co/#/round/0x4c9cb06c6b69ac42a8737389c12dd77a1cc90d04 

Project A: (30 raw votes, 20 final votes) 
Donor 1 gives 15 GcV tokens
Donor 2 gives 15 GcV tokens

Project B: (20 raw and final votes) 
Donor 1 gives 10 GcV tokens
Donor 2 gives 10 GcV tokens

I believe that if the cap is working correctly, the matching estimates split should be 50-50. If it's not working, then I would expect Project A to have a slightly higher match % ? 

**Results**

We observed a 60/40 split in matching % on the Round Stats page, which indicates that the cap may not be working as expected. 

![Image](https://github.com/gitcoinco/allo-indexer/assets/26017180/adc676ab-10cc-4264-9277-f835bc9ff6b0)

**Comment by gravityblast** [comment]
I think you should try testing it in staging, we didn’t release the feature in prod for the indexer On 26 Aug 2023, at 05:51, Michelle Ma ***@***.***> wrote:﻿
Update from 8/25: Spun up a test round and donated to two projects following the below parameters:
Round: https://manager.gitcoin.co/#/round/0x4c9cb06c6b69ac42a8737389c12dd77a1cc90d04
Project A: (30 raw votes, 20 final votes)
Donor 1 gives 15 GcV tokens
Donor 2 gives 15 GcV tokens
Project B: (20 raw and final votes)
Donor 1 gives 10 GcV tokens
Donor 2 gives 10 GcV tokens
I believe that if the cap is working correctly, the matching estimates split should be 50-50. If it's not working, then I would expect Project A to have a slightly higher match % ?
Results
We observed a 60/40 split in matching % on the Round Stats page, which indicates that the cap may not be working as expected.

**Comment by michellema1208** [comment]
confirmed it was working on staging - this is ready to move to prod!
