### ISSUE TITLE
use newline delimited JSON for the votes collection

### ISSUE THREAD

**Issue by boudra** [gitcoinco/allo-indexer#293]
the votes collection is append only, we could benefit from just writing JSON objects in append mode instead of serializing / deserializing a huge JSON array

ideally we would implement this in the indexer and remove the collection / storage functionality from Chainsauce before doing this

**Comment by bard** [comment]
@boudra we want to move away from files and toward a uniform storage strategy, see #268

**Comment by boudra** [comment]
closing this as we're probably moving to an SQL database
