### ISSUE TITLE
arbitrum stopped indexing

### ISSUE THREAD

**Issue by boudra** [gitcoinco/allo-indexer#296]
users noticed data was stale, checking the logs I noticed there were no blockchain indexer related logs for Arbitrum, the other chains we're indexing fine, somehow the chain indexer stopped working.

more context: https://discord.com/channels/562828676480237578/1153792347432292462
logs: https://app.datadoghq.eu/logs?query=%40fly.app.name%3A%22indexer-production%22%20%40chain%3A42161&cols=host%2Cservice&index=*&messageDisplay=inline&refresh_mode=paused&stream_sort=desc&viz=stream&from_ts=1695042060000&to_ts=1695222060000&live=false

**Comment by bard** [comment]
Closing as handled.
