### ISSUE TITLE
fix: number.toString issue

### ISSUE THREAD

**Issue by vacekj** [gitcoinco/allo-indexer#319]
when converting very big numbers to strings using `.toString()`, js uses scientific notation above a certain treshold (`123e12`). this breaks parsing this string back into BigInts. we avoid this by first converting this number to bigints, then converting to string, then converting back to bigint.

**Comment by gravityblast** [comment]
if we have very bignumber as normal `number` the problem is before the call to `toString`. we should create it directly as `bigint` and not convert it after

**Comment by gravityblast** [comment]
or you can use .toLocaleString("fullwide", { useGrouping: false })
