### ISSUE TITLE
Verify that data in the Allo Indexer is correct

### ISSUE THREAD

**Issue by boudra** [gitcoinco/allo-indexer#4]
The core work on the indexer is now complete: https://github.com/gitcoinco/allo-indexer

I would like to spend some time to verify the data integrity and make sure it's all correct, by comparing it to The Graph or the current API.

**Comment by hmrtn** [comment]
There seems to be an error in our `amountInUSD` field. The amount in USD is very large and the variance between these values for all round projects is small. I think there may either be 1. a summation error or 2. a vote for every project whose amount is very large (BigNumber?) and somehow throwing off all projects. 

This can be seen here: https://grants-stack-indexer.fly.dev/data/1/rounds/0xD95A1969c41112cEE9A2c931E849bCef36a16F4C/projects.json

**Comment by boudra** [comment]
Thanks @hmrtn I'll check!!

**Comment by boudra** [comment]
Hey @hmrtn I have updated Fly with some fixes, let me know if you still see issues!
