### ISSUE TITLE
Make linter stricter

### ISSUE THREAD

**Issue by boudra** [gitcoinco/allo-indexer#48]
I noticed things are getting a bit out of control wit `any` types and null assertions, especially in the calculator. I would like to configure **eslint** to make these **errors and not warnings** so they fail CI, and also force files to be formatted with prettier, but because we already have them we also have to fix them at the same time, we cannot just change the config and call it a day. Ideally we would do this as soon as we can before things get hard to refactor.

Adding this issue as a reminder.

@gravityblast @vacekj @hmrtn any thoughts here?

**Comment by vacekj** [comment]
Agreed, i can set it up same as the frontend repo. eslint fails ci even for warnings when CI=true

**Comment by bard** [comment]
Worth considering an org-wide, git-installable eslintrc?
